#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Кнопки мыши
DATA_CODE_KEYS = [
    dict(name='Левая кнопка мыши',
         group=1,
         # constant='',
         code_decimal=1,
         alias=(',левая кнопка мыши,левая кнопка,лкм,lbutton,lclick,left mouse button,left mouse,left button,'),
         ),
    dict(name='Правая кнопка мыши',
         group=1,
         # constant='',
         code_decimal=2,
         alias=(',правая кнопка мыши,правая кнопка,пкм,rbutton,rclick,right mouse button,right mouse,right button,'),
         ),
    dict(name='Средняя кнопка мыши',
         group=1,
         # constant='',
         code_decimal=4,
         alias=(',средняя кнопка мыши,средняя кнопка,скм,mbutton,mclick,middle mouse button,middle mouse,middle button,'),
         ),
]

# Клавиши-модификаторы
DATA_CODE_KEYS.extend([
    dict(name='Shift',
         group=2,
         constant='#SHIFT',
         code_decimal=16,
         alias=(',shift,шифт,левый шифт,left shift,'),
         ),
    dict(name='Ctrl',
         group=2,
         constant='#CTRL',
         code_decimal=17,
         alias=(',ctrl,контрол,контрл,левый контрл,left ctrl,'),
         ),
    dict(name='Alt',
         group=2,
         constant='#ALT',
         code_decimal=18,
         alias=(',alt,альт,левый альт,left alt,'),
         ),
])

# Специальные клавиши
DATA_CODE_KEYS.extend([
    dict(name='Backspace',
         group=3,
         constant='#BACKSPACE',
         code_decimal=8,
         alias=(',backspace,back space,бекспейс,бекспэйс,бэкспейс,бэкспэйс,бек спейс,бек спэйс,бэк спейс,бэк спэйс,'),
         ),
    dict(name='Tab',
         group=3,
         constant='#TAB',
         code_decimal=9,
         alias=(',tab,таб,табуляция,'),
         ),
    dict(name='Enter',
         group=3,
         constant='#ENTER',
         code_decimal=13,
         alias=(',enter,ентер,энтер,ентэр,энтер,ввод,'),
         ),
    dict(name='Pause',
         group=3,
         constant='#PAUSE',
         code_decimal=19,
         alias=(',pause,паузе,паусе,паузэ,паусэ,пауза,'),
         ),
    dict(name='CapsLock',
         group=3,
         constant='#CAPSLOCK',
         code_decimal=20,
         alias=(',capslock,caps lock,капслок,капс лок,заглавные,капс,'),
         ),
    dict(name='Esc',
         group=3,
         constant='#ESC',
         code_decimal=27,
         alias=(',esc,эск,эскейп,эскэйп, ескейп,ескэйп,выйти,'),
         ),
    dict(name='Insert',
         group=3,
         constant='#INSERT',
         code_decimal=45,
         alias=(',insert,инсерт,инсэрт,вставить,вставка,'),
         ),
    dict(name='Delete',
         group=3,
         constant='#DELETE',
         code_decimal=46,
         alias=(',delete,delet,делит,дэлит,делейт,дэлейт,дэлэйт,'),
         ),
    dict(name='ScrollLock',
         group=3,
         constant='#SCROLLLOCK',
         code_decimal=145,
         alias=(',scrolllock,scroll lock,скроллок,скрол лок,скролллок,скролл лок,'),
         ),
    dict(name='PrintScreen',
         group=3,
         constant='#PRINTSCREEN',
         code_decimal=154,
         alias=(',printscreen,print screen,принтскрин,принт скрин,скриншот,'),
         ),
])

# Windows клавиши
DATA_CODE_KEYS.extend([
    dict(name='Левая клавиша Windows',
         group=4,
         constant='#WIN, #LWIN',
         code_decimal=91,
         alias=(',левая клавиша windows,левая windows,windows,win,lwin,левая виндовс,лвин,элвин,'),
         ),
    dict(name='Правая клавиша Windows',
         group=4,
         constant='#RWIN',
         code_decimal=92,
         alias=(',правая клавиша windows,правая windows,rwin,правая виндовс,праввин,прав вин,'),
         ),
    dict(name='Клавиша Applications',
         group=4,
         # constant='',
         code_decimal=93,
         alias=(',клавиша applications,applications,application,эпликэйшен,апликэйшен,эпликейшен,апликейшен,эпликэйшэн,апликэйшэн,эпликейшэн,апликейшэн,эпликатион,апликатион,'),
         ),
])

# Клавиши управления курсором
DATA_CODE_KEYS.extend([
    dict(name='PageUp',
         group=5,
         constant='#PAGEUP',
         code_decimal=33,
         alias=(',pageup,page up,пейджап,пэйджап,пейдж ап,пэйдж ап,страница вверх,лист вверх,'),
         ),
    dict(name='PageDown',
         group=5,
         constant='#PAGEDOWN',
         code_decimal=34,
         alias=(',pagedown,pagedn,page down,page dn,пейдждовн,пэйдждовн,пейдж довн,пэйдж довн,страница вниз,лист вниз,'),
         ),
    dict(name='End',
         group=5,
         constant='#END',
         code_decimal=35,
         alias=(',end,энд,конец,'),
         ),
    dict(name='Home',
         group=5,
         constant='#HOME',
         code_decimal=36,
         alias=(',home,хоме,хомэ,хоум,домой,в начало,'),
         ),
    dict(name='Left',
         group=5,
         constant='#LEFT',
         code_decimal=37,
         alias=(',стрелка влево,left,влево,'),
         ),
    dict(name='Up',
         group=5,
         constant='#UP',
         code_decimal=38,
         alias=(',стрелка вверх,up,вверх,'),
         ),
    dict(name='Right',
         group=5,
         constant='#RIGHT',
         code_decimal=39,
         alias=(',стрелка вправо,right,вправо,'),
         ),
    dict(name='Down',
         group=5,
         constant='#DOWN',
         code_decimal=40,
         alias=(',стрелка вниз,down,вниз,'),
         ),
])

# Функциональные клавиши
DATA_CODE_KEYS.extend([
    dict(name='F1',
         group=6,
         constant='#F1',
         code_decimal=112,
         alias=(',f1,f 1,ф1,ф 1,эф1,эф 1,'),
         ),
    dict(name='F2',
         group=6,
         constant='#F2',
         code_decimal=113,
         alias=(',f2,f 2,ф2,ф 2,эф2,эф 2,'),
         ),
    dict(name='F3',
         group=6,
         constant='#F3',
         code_decimal=114,
         alias=(',f3,f 3,ф3,ф 3,эф3,эф 3,'),
         ),
    dict(name='F4',
         group=6,
         constant='#F4',
         code_decimal=115,
         alias=(',f4,f 4,ф4,ф 4,эф4,эф 4,'),
         ),
    dict(name='F5',
         group=6,
         constant='#F5',
         code_decimal=116,
         alias=(',f5,f 5,ф5,ф 5,эф5,эф 5,'),
         ),
    dict(name='F6',
         group=6,
         constant='#F6',
         code_decimal=117,
         alias=(',f6,f 6,ф6,ф 6,эф6,эф 6,'),
         ),
    dict(name='F7',
         group=6,
         constant='#F7',
         code_decimal=118,
         alias=(',f7,f 7,ф7,ф 7,эф7,эф 7,'),
         ),
    dict(name='F8',
         group=6,
         constant='#F8',
         code_decimal=119,
         alias=(',f8,f 8,ф8,ф 8,эф8,эф 8,'),
         ),
    dict(name='F9',
         group=6,
         constant='#F9',
         code_decimal=120,
         alias=(',f9,f 9,ф9,ф 9,эф9,эф 9,'),
         ),
    dict(name='F10',
         group=6,
         constant='#F10',
         code_decimal=121,
         alias=(',f10,f 10,ф10,ф 10,эф10,эф 10,'),
         ),
    dict(name='F11',
         group=6,
         constant='#F11',
         code_decimal=122,
         alias=(',f11,f 11,ф11,ф 11,эф11,эф 11,'),
         ),
    dict(name='F12',
         group=6,
         constant='#F12',
         code_decimal=123,
         alias=(',f12,f 12,ф12,ф 12,эф12,эф 12,'),
         ),
])

# Цифры
DATA_CODE_KEYS.extend([
    dict(name='0',
         group=7,
         constant='#0',
         code_decimal=48,
         alias=(',0,'),
         ),
    dict(name='1',
         group=7,
         constant='#1',
         code_decimal=49,
         alias=(',1,'),
         ),
    dict(name='2',
         group=7,
         constant='#2',
         code_decimal=50,
         alias=(',2,'),
         ),
    dict(name='3',
         group=7,
         constant='#3',
         code_decimal=51,
         alias=(',3,'),
         ),
    dict(name='4',
         group=7,
         constant='#4',
         code_decimal=52,
         alias=(',4,'),
         ),
    dict(name='5',
         group=7,
         constant='#5',
         code_decimal=53,
         alias=(',5,'),
         ),
    dict(name='6',
         group=7,
         constant='#6',
         code_decimal=54,
         alias=(',6,'),
         ),
    dict(name='7',
         group=7,
         constant='#7',
         code_decimal=55,
         alias=(',7,'),
         ),
    dict(name='8',
         group=7,
         constant='#8',
         code_decimal=56,
         alias=(',8,'),
         ),
    dict(name='9',
         group=7,
         constant='#9',
         code_decimal=57,
         alias=(',9,'),
         ),
])

# Буквы ENG
DATA_CODE_KEYS.extend([
    dict(name='Space',
         group=8,
         constant='#SPACE',
         code_decimal=32,
         alias=(',space,пробел,'),
         ),
    dict(name='A',
         group=8,
         constant='#A',
         code_decimal=65,
         alias=(',a,'),
         ),
    dict(name='B',
         group=8,
         constant='#B',
         code_decimal=66,
         alias=(',b,'),
         ),
    dict(name='C',
         group=8,
         constant='#C',
         code_decimal=67,
         alias=(',c,'),
         ),
    dict(name='D',
         group=8,
         constant='#D',
         code_decimal=68,
         alias=(',d,'),
         ),
    dict(name='E',
         group=8,
         constant='#E',
         code_decimal=69,
         alias=(',e,'),
         ),
    dict(name='F',
         group=8,
         constant='#F',
         code_decimal=70,
         alias=(',f,'),
         ),
    dict(name='G',
         group=8,
         constant='#G',
         code_decimal=71,
         alias=(',g,'),
         ),
    dict(name='H',
         group=8,
         constant='#H',
         code_decimal=72,
         alias=(',h,'),
         ),
    dict(name='I',
         group=8,
         constant='#I',
         code_decimal=73,
         alias=(',i,'),
         ),
    dict(name='J',
         group=8,
         constant='#J',
         code_decimal=74,
         alias=(',j,'),
         ),
    dict(name='K',
         group=8,
         constant='#K',
         code_decimal=75,
         alias=(',k,'),
         ),
    dict(name='L',
         group=8,
         constant='#L',
         code_decimal=76,
         alias=(',l,'),
         ),
    dict(name='M',
         group=8,
         constant='#M',
         code_decimal=77,
         alias=(',m,'),
         ),
    dict(name='N',
         group=8,
         constant='#N',
         code_decimal=78,
         alias=(',n,'),
         ),
    dict(name='O',
         group=8,
         constant='#O',
         code_decimal=79,
         alias=(',o,'),
         ),
    dict(name='P',
         group=8,
         constant='#P',
         code_decimal=80,
         alias=(',p,'),
         ),
    dict(name='Q',
         group=8,
         constant='#Q',
         code_decimal=81,
         alias=(',q,'),
         ),
    dict(name='R',
         group=8,
         constant='#R',
         code_decimal=82,
         alias=(',r,'),
         ),
    dict(name='S',
         group=8,
         constant='#S',
         code_decimal=83,
         alias=(',s,'),
         ),
    dict(name='T',
         group=8,
         constant='#T',
         code_decimal=84,
         alias=(',t,'),
         ),
    dict(name='U',
         group=8,
         constant='#U',
         code_decimal=85,
         alias=(',u,'),
         ),
    dict(name='V',
         group=8,
         constant='#V',
         code_decimal=86,
         alias=(',v,'),
         ),
    dict(name='W',
         group=8,
         constant='#W',
         code_decimal=87,
         alias=(',w,'),
         ),
    dict(name='X',
         group=8,
         constant='#X',
         code_decimal=88,
         alias=(',x,'),
         ),
    dict(name='Y',
         group=8,
         constant='#Y',
         code_decimal=89,
         alias=(',y,'),
         ),
    dict(name='Z',
         group=8,
         constant='#Z',
         code_decimal=90,
         alias=(',z,'),
         ),
])

# Цифровой блок
DATA_CODE_KEYS.extend([
    dict(name='NumPad 0',
         group=9,
         constant='#NP0',
         code_decimal=96,
         alias=(',numpad0,numpad 0,np0,np 0,'),
         ),
    dict(name='NumPad 1',
         group=9,
         constant='#NP1',
         code_decimal=97,
         alias=(',numpad1,numpad 1,np1,np 1,'),
         ),
    dict(name='NumPad 2',
         group=9,
         constant='#NP2',
         code_decimal=98,
         alias=(',numpad2,numpad 2,np2,np 2,'),
         ),
    dict(name='NumPad 3',
         group=9,
         constant='#NP3',
         code_decimal=99,
         alias=(',numpad3,numpad 3,np3,np 3,'),
         ),
    dict(name='NumPad 4',
         group=9,
         constant='#NP4',
         code_decimal=100,
         alias=(',numpad4,numpad 4,np4,np 4,'),
         ),
    dict(name='NumPad 5',
         group=9,
         constant='#NP5',
         code_decimal=101,
         alias=(',numpad5,numpad 5,np5,np 5,'),
         ),
    dict(name='NumPad 6',
         group=9,
         constant='#NP6',
         code_decimal=102,
         alias=(',numpad6,numpad 6,np6,np 6,'),
         ),
    dict(name='NumPad 7',
         group=9,
         constant='#NP7',
         code_decimal=103,
         alias=(',numpad7,numpad 7,np7,np 7,'),
         ),
    dict(name='NumPad 8',
         group=9,
         constant='#NP8',
         code_decimal=104,
         alias=(',numpad8,numpad 8,np8,np 8,'),
         ),
    dict(name='NumPad 9',
         group=9,
         constant='#NP9',
         code_decimal=105,
         alias=(',numpad9,numpad 9,np9,np 9,'),
         ),
    dict(name='NumPad *',
         group=9,
         constant='#NPMULT',
         code_decimal=106,
         alias=(',numpad*,numpad *,np*,np *,npmult,'),
         ),
    dict(name='NumPad +',
         group=9,
         constant='#NPADD',
         code_decimal=107,
         alias=(',numpad+,numpad +,np+,np +,npadd,'),
         ),
    dict(name='NumPad -',
         group=9,
         constant='#NPSUB',
         code_decimal=109,
         alias=(',numpad-,numpad -,np-,np -,npsub,'),
         ),
    dict(name='NumPad .',
         group=9,
         constant='#NPDOT',
         code_decimal=110,
         alias=(',numpad.,numpad .,np.,np .,npdot,'),
         ),
    dict(name='NumPad /',
         group=9,
         constant='#NPDIV',
         code_decimal=111,
         alias=(',numpad/,numpad /,np/,np /,npdiv,'),
         ),
    dict(name='NumLock',
         group=9,
         constant='#NUMLOCK',
         code_decimal=144,
         alias=(',numlock,num lock,намлок,нам лок,нумлок,'),
         ),
])

# Символьные клавиши
DATA_CODE_KEYS.extend([
    dict(name=';',
         group=10,
         constant='#SEMICOLON',
         code_decimal=186,
         alias=(',;,точка с запятой,'),
         ),
    dict(name='=',
         group=10,
         constant='#EQUAL',
         code_decimal=187,
         alias=(',=,equal,равно,'),
         ),
    dict(name=',',
         group=10,
         constant='#COMMA',
         code_decimal=188,
         alias=(',,,comma,запятая,'),
         ),
    dict(name='-',
         group=10,
         constant='#MINUS',
         code_decimal=189,
         alias=(',-,minus,минус,'),
         ),
    dict(name='.',
         group=10,
         constant='#DOT',
         code_decimal=190,
         alias=(',.,dot,point,period,точка,'),
         ),
    dict(name='/',
         group=10,
         constant='#SLASH',
         code_decimal=191,
         alias=(',/,slash,слеш,слэш,'),
         ),
    dict(name='~',
         group=10,
         constant='#TILDE',
         code_decimal=192,
         alias=(',~,tilde,тильда,'),
         ),
    dict(name='[',
         group=10,
         constant='#OBRACK',
         code_decimal=219,
         alias=(',[,obrack,левая квадратная скобка,'),
         ),
    dict(name='\\',
         group=10,
         constant='#BACKSLASH',
         code_decimal=220,
         alias=(',\\,backslash,обратныйслеш,обратный слэш,'),
         ),
    dict(name=']',
         group=10,
         constant='#CBRACK',
         code_decimal=221,
         alias=(',],cbrack,правая квадратная скобка,'),
         ),
    dict(name="'",
         group=10,
         constant='#QUOTE',
         code_decimal=222,
         alias=(",',quote,одинарная кавычка,"),
         ),
])


# --------------------------------------------------------------------------------------------------

"""
DATA_CODE_KEYS.extend([
    dict(name='',
         group=1,
          constant='',
         code_decimal=,
         alias=(',,'),
         ),
])
"""
